/**
 * Domain error codes — map.md §48.
 *
 * The frontend switches on `code`, never on `message`, so these strings are part
 * of the API contract: rename one and you break a client.
 */
export const ErrorCodes = {
  // auth / tenancy
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  ORGANIZATION_REQUIRED: 'ORGANIZATION_REQUIRED',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  BUSINESS_CATEGORY_NOT_FOUND: 'BUSINESS_CATEGORY_NOT_FOUND',
  INSUFFICIENT_PERMISSION: 'INSUFFICIENT_PERMISSION',
  MEMBER_NOT_FOUND: 'MEMBER_NOT_FOUND',
  LAST_OWNER_PROTECTED: 'LAST_OWNER_PROTECTED',

  // catalog
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  ITEM_NOT_FOUND: 'ITEM_NOT_FOUND',
  TAX_RATE_NOT_FOUND: 'TAX_RATE_NOT_FOUND',
  PACKAGE_NOT_FOUND: 'PACKAGE_NOT_FOUND',
  REUSABLE_BLOCK_NOT_FOUND: 'REUSABLE_BLOCK_NOT_FOUND',

  // templates
  TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
  TEMPLATE_NOT_PUBLISHED: 'TEMPLATE_NOT_PUBLISHED',
  TEMPLATE_VERSION_NOT_FOUND: 'TEMPLATE_VERSION_NOT_FOUND',
  TEMPLATE_VERSION_IMMUTABLE: 'TEMPLATE_VERSION_IMMUTABLE',
  TEMPLATE_SCHEMA_INVALID: 'TEMPLATE_SCHEMA_INVALID',
  FIELD_SCHEMA_INVALID: 'FIELD_SCHEMA_INVALID',
  FIELD_REQUIRED: 'FIELD_REQUIRED',
  FIELD_TYPE_INVALID: 'FIELD_TYPE_INVALID',
  FORMULA_INVALID: 'FORMULA_INVALID',
  FORMULA_CIRCULAR_REFERENCE: 'FORMULA_CIRCULAR_REFERENCE',
  UNKNOWN_VARIABLE_REFERENCE: 'UNKNOWN_VARIABLE_REFERENCE',

  // documents
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  DOCUMENT_NOT_EDITABLE: 'DOCUMENT_NOT_EDITABLE',
  DOCUMENT_ALREADY_ACCEPTED: 'DOCUMENT_ALREADY_ACCEPTED',
  DOCUMENT_REVISION_IMMUTABLE: 'DOCUMENT_REVISION_IMMUTABLE',
  DOCUMENT_REVISION_NOT_FOUND: 'DOCUMENT_REVISION_NOT_FOUND',
  DOCUMENT_NOT_GENERATED: 'DOCUMENT_NOT_GENERATED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
  CONCURRENT_EDIT_CONFLICT: 'CONCURRENT_EDIT_CONFLICT',

  // public sharing
  SHARE_LINK_INVALID: 'SHARE_LINK_INVALID',
  SHARE_LINK_EXPIRED: 'SHARE_LINK_EXPIRED',
  SHARE_LINK_REVOKED: 'SHARE_LINK_REVOKED',

  // rendering
  PDF_RENDERER_NOT_CONFIGURED: 'PDF_RENDERER_NOT_CONFIGURED',

  // billing
  PLAN_NOT_FOUND: 'PLAN_NOT_FOUND',
  PLAN_CODE_TAKEN: 'PLAN_CODE_TAKEN',
  PLAN_IN_USE: 'PLAN_IN_USE',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  BILLING_NOT_CONFIGURED: 'BILLING_NOT_CONFIGURED',
  GATEWAY_PLAN_NOT_LINKED: 'GATEWAY_PLAN_NOT_LINKED',
  GATEWAY_REQUEST_FAILED: 'GATEWAY_REQUEST_FAILED',
  CHECKOUT_SIGNATURE_INVALID: 'CHECKOUT_SIGNATURE_INVALID',
  WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
  PLAN_LIMIT_REACHED: 'PLAN_LIMIT_REACHED',
  SUBSCRIPTION_INACTIVE: 'SUBSCRIPTION_INACTIVE',
  PLATFORM_ADMIN_REQUIRED: 'PLATFORM_ADMIN_REQUIRED',
  DISCOUNT_NOT_FOUND: 'DISCOUNT_NOT_FOUND',
  DISCOUNT_NOT_APPLICABLE: 'DISCOUNT_NOT_APPLICABLE',
  DISCOUNT_CODE_TAKEN: 'DISCOUNT_CODE_TAKEN',
  BLOG_POST_NOT_FOUND: 'BLOG_POST_NOT_FOUND',
  BLOG_POST_SLUG_TAKEN: 'BLOG_POST_SLUG_TAKEN',

  // generic
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
